
#                                            Numpy Tutorial 

# Why use NumPy?

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

In [37]:
import numpy as np 
import math 
import warnings
warnings.filterwarnings("ignore")
from IPython.display import Image

## 1D array, 2D array, ndarray, vector, matrix,Tensors

A vector is an array with a single dimension (there’s no difference between row and column vectors), while a matrix refers to an array with two dimensions. For 3-D or higher dimensional arrays, the term tensor is also commonly used.

## Create a basic array
This section covers np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype



In [45]:
list1 = [10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [46]:
# Display the type of an object
type(list1)

list

In [47]:
#Convert list to Numpy Array
arr1 = np.array(list1)

In [48]:
#Memory address of an array object
arr1.data

In [49]:
# Display type of an object
type(arr1)

numpy.ndarray

In [51]:
#Datatype of array
arr1.dtype

dtype('int32')

In [52]:
# Convert Integer Array to FLOAT
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [53]:
# Generate evenly spaced numbers (space =1) between 0 to 10
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
# Generate numbers between 0 to 100 with a space of 10
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [55]:
# Generate numbers between 10 to 100 with a space of 10 in descending order
np.arange(100,10,-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [59]:
arr2 = np.array([[1,2,3],[1,1,1]])
arr2 

array([[1, 2, 3],
       [1, 1, 1]])

In [60]:
#Shape of Array
arr1.shape , arr2.shape

((6,), (2, 3))

In [61]:
# Size of array
arr1.size , arr2.size

(6, 6)

In [62]:
# Dimension 
arr1.ndim , arr2.ndim 

(1, 2)

In [65]:
# Datatype of object
arr2.dtype

dtype('int32')

In [66]:
# Bytes consumed by one element of an array object
arr2.itemsize

4

In [69]:
# Bytes consumed by an array object
arr2.nbytes

24

In [73]:
# length of array
len(arr2)


2

In [76]:
# Generate an array of zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [82]:
# Generate an array of ones with given shape
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [85]:
# Repeat 10 five times in an array
np.repeat(10,3)

array([10, 10, 10])

In [86]:
# Repeat each element in array/list 'b' thrice
b = [1,2,3,4]
np.repeat(b,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [87]:
# Array of 10's
np.full(3,10)


array([10, 10, 10])

In [90]:
np.ones_like(10)

array(1)

In [92]:
# Generate array of Odd numbers
ar1 = np.arange(1,20)
ans = ar1[ar1%2==1]
ans

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [93]:
# Generate array of even numbers
ar1 = np.arange(1,20)
ar1[ar1%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [94]:
# Generate evenly spaced 4 numbers between 10 to 20.
np.linspace(10,20,4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [95]:
# Generate evenly spaced 11 numbers between 10 to 20.
np.linspace(10,20,15)


array([10.        , 10.71428571, 11.42857143, 12.14285714, 12.85714286,
       13.57142857, 14.28571429, 15.        , 15.71428571, 16.42857143,
       17.14285714, 17.85714286, 18.57142857, 19.28571429, 20.        ])

In [96]:
# Create an array of random values
np.random.random(4)


array([0.70130884, 0.44175175, 0.22345572, 0.16067744])

In [98]:
# Generate an array of Random Integer numbers
np.random.randint(0,100,6)

array([ 3, 86,  8, 38, 80, 27])

In [112]:
# Using random.seed we can generate same number of Random numbers
np.random.seed(123)
np.random.randint(0,100,10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [110]:
np.random.randn(10)

array([-0.2299375 , -1.28359884, -2.71119174, -1.52241044, -1.41620705,
        1.10854366,  1.13102858,  0.49860031,  1.17902193,  1.32268437])

In [129]:
# Generate array of Random float numbers
f1 = np.random.uniform(5,10,10)
f1

array([9.34521773, 5.67478125, 7.91051226, 7.81108133, 5.4518006 ,
       8.82082369, 7.36455072, 8.07414876, 8.63097521, 6.60744156])

In [130]:
# Extract Integer part
np.floor(f1)

array([9., 5., 7., 7., 5., 8., 7., 8., 8., 6.])

In [131]:
# Truncate decimal part
np.trunc(f1)

array([9., 5., 7., 7., 5., 8., 7., 8., 8., 6.])

In [132]:
# Convert Float Array to Integer array
f1.astype(int)

array([9, 5, 7, 7, 5, 8, 7, 8, 8, 6])

In [141]:
# Normal distribution (mean=0 and variance=1)
b2 = np.random.randn(10)
b2

array([ 0.34020214, -1.13320326, -0.44388393,  2.28008424, -0.76230112,
        0.117435  , -0.65094869,  0.45886268, -0.61012018, -0.2339279 ])

In [144]:
# Enumerate for Numpy Arrays
for index,value in np.ndenumerate(b2):
    print(index,value)

(0,) 0.3402021440266375
(1,) -1.1332032553014906
(2,) -0.4438839252596832
(3,) 2.280084244216001
(4,) -0.7623011246188897
(5,) 0.11743499605854721
(6,) -0.6509486881811433
(7,) 0.45886267620982396
(8,) -0.6101201827305474
(9,) -0.23392790107076064



# Operations on an Array¶


In [145]:
arr2 = np.arange(1,20)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [146]:
# Sum of all elements in an array
arr2.sum()

190

In [147]:
# Cumulative Sum
np.cumsum(arr2)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190], dtype=int32)

In [148]:
# Find Minimum number in an array
arr2.min()

1

In [149]:
# Find MAX number in an array
arr2.max()

19

In [154]:
# Find INDEX of Minimum number in an array
arr2.argmin()

0

In [155]:
# Find INDEX of MAX number in an array
arr2.argmax()

18

In [156]:
# Find mean of all numbers in an array
arr2.mean()


10.0

In [157]:
# Find median of all numbers present in arr2
np.median(arr2)


10.0

In [158]:
# Variance
np.var(arr2)

30.0

In [159]:
# Standard deviation
np.std(arr2)

5.477225575051661

In [160]:
# Calculating percentiles
np.percentile(arr2,70)


13.6

In [161]:
# 10th & 70th percentile
np.percentile(arr2,[10,70])


array([ 2.8, 13.6])

# Operations on a 2D Array¶


In [163]:
A = np.array([[1,2,3,4],[11,12,13,1],[22,33,0,0],[12,11,1,3]])
A 

array([[ 1,  2,  3,  4],
       [11, 12, 13,  1],
       [22, 33,  0,  0],
       [12, 11,  1,  3]])

In [164]:
# SUM of all numbers in a 2D array
A.sum()

129

In [168]:
# MAX number in a 2D array
A.max()
np.max(A)

33

In [169]:
# Minimum
A.min()

0

In [176]:
# Column wise mimimum value 
np.min(A,axis=0)

array([1, 2, 0, 0])

In [178]:
# row wise mimimum value 
np.amin(A,axis=1)

array([1, 1, 0, 1])

In [179]:
# Mean of all numbers in a 2D array
A.mean()

8.0625

In [180]:
# Mean

np.mean(A)


8.0625

In [181]:
# Median
np.median(A)

3.5

In [182]:
# 50 percentile = Median
np.percentile(A,50)


3.5

In [183]:
print(np.var(A))
print(np.std(A))


79.55859375
8.919562419199723


In [185]:
# enumarate for numpy 2D array 
for index, value in np.ndenumerate(A):
    print(index,value) 

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 11
(1, 1) 12
(1, 2) 13
(1, 3) 1
(2, 0) 22
(2, 1) 33
(2, 2) 0
(2, 3) 0
(3, 0) 12
(3, 1) 11
(3, 2) 1
(3, 3) 3


# Reading elements of an array¶


In [186]:
a = np.array([7,5,3,9,0,2])

In [187]:
# access first element of the array 
a[0]

7

In [188]:
# Access all elements of Array except first one.
a[1:]

array([5, 3, 9, 0, 2])

In [189]:
# Fetch 2nd , 3rd & 4th value from the Array
a[1:4]

array([5, 3, 9])

In [190]:
# Get last element of the array
a[-1]

2

In [194]:
a[-3:],a[-3:-1]

(array([9, 0, 2]), array([9, 0]))

# Replace elements in Array¶


In [195]:
ar = np.arange(1,20)
ar 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [196]:
# Replace EVEN numbers with ZERO
rep1 = np.where(ar%2==0,0,ar)
rep1

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0, 17,
        0, 19])

In [197]:
ar2 = np.array([10, 20 , 30 , 10 ,10 ,20, 20])
ar2

array([10, 20, 30, 10, 10, 20, 20])

In [199]:
# replace 10 with 99
ar10_99 = np.where(ar2==10,99,ar2)
ar10_99

array([99, 20, 30, 99, 99, 20, 20])

In [200]:
p2 = np.arange(0,100,10)
p2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [205]:
# Replace values at INDEX loc 0,3,5 with 33,55,99
np.put(p2,[0,3,5],[44,66])

In [206]:
p2

array([44, 10, 20, 66, 40, 44, 60, 70, 80, 90])

# Missing Values in an array¶


In [207]:
a = np.array([10 ,np.nan,20,30,60,np.nan,90,np.inf])
a

array([10., nan, 20., 30., 60., nan, 90., inf])

In [208]:
# Search for missing values and return as a boolean array
np.isnan(a)

array([False,  True, False, False, False,  True, False, False])

In [209]:
# Index of missing values in an array
np.where(np.isnan(a))

(array([1, 5], dtype=int64),)

In [213]:
# Replace all missing values with 99
a[np.isnan(a)]=99
a

array([10., 99., 20., 30., 60., 99., 90., inf])

In [214]:
# Check if array has any NULL value
np.isnan(a).any()

False

In [216]:
A = np.array([[1,2,np.nan,4] , [np.nan,6,7,8] , [10 , np.nan , 12 ,13] , [14,15,16,17]])
A

array([[ 1.,  2., nan,  4.],
       [nan,  6.,  7.,  8.],
       [10., nan, 12., 13.],
       [14., 15., 16., 17.]])

In [217]:
# Search for missing values and return as a boolean array


In [218]:
np.where(np.isnan(A))

(array([0, 1, 2], dtype=int64), array([2, 0, 1], dtype=int64))

# Reshape Arrays

In [219]:
a = np.zeros((10, 2))

In [220]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [221]:
# A transpose makes the array non-contiguous
b = a.T


In [222]:
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [223]:
# Taking a view makes it possible to modify the shape without modifying the initial object.

c= b.view()
c


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [225]:
c.shape = (20)

AttributeError: Incompatible shape for in-place modification. Use `.reshape()` to make a copy with the desired shape.

In [230]:
a = np.arange(6).reshape((2,3))
a

array([[0, 1, 2],
       [3, 4, 5]])

In [227]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [231]:
a.size

6

In [232]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [233]:
np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])

In [234]:
np.reshape(a, 6, order='F')

array([1, 4, 2, 5, 3, 6])

In [235]:
np.reshape(a, (3,-1))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [237]:
np.reshape(a,(3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [239]:
np.reshape(a,(3,-1)) # # the unspecified value is inferred to be 2

array([[1, 2],
       [3, 4],
       [5, 6]])

# Stack Arrays Vertically¶


In [240]:
a = np.zeros(20).reshape(2,-1)
b = np.repeat(1, 20).reshape(2,-1)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [241]:
b

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [243]:
c = np.ones(20).reshape(2,10)
c

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [245]:
c.dtype

dtype('float64')

In [249]:
b.dtype

dtype('int32')

In [247]:
np.vstack([a,b])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [248]:
np.vstack([a,b,c])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [250]:
np.vstack([1,b]) # shape should be same

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 1 and the array at index 1 has size 10

In [253]:
a1 = np.array([[1],[2],[3]])
b1 = np.array([[4],[5],[6]])

In [254]:
a1

array([[1],
       [2],
       [3]])

In [257]:
np.vstack([a1,b1])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])


# Stack Arrays Horizontally

In [258]:
np.hstack([a1,b1])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [261]:
np.hstack([a,b])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [265]:
### hstack & vstack
arr1 = np.array([[7,13,14],[18,10,17],[11,12,19]])
arr2= np.array([16,6,1])
arr3= np.array([[5,8,4,3]])


np.hstack((np.vstack((arr1,arr2)),np.transpose(arr3)))

array([[ 7, 13, 14,  5],
       [18, 10, 17,  8],
       [11, 12, 19,  4],
       [16,  6,  1,  3]])

# Common items between two Arrays¶


In [269]:
c1 = np.array([10,20,30,40,50])
c2 = np.array([12,20,33,40,44,10])


In [270]:
np.intersect1d(c1,c2)

array([10, 20, 40])

# Remove Common Elements¶


In [271]:

np.setdiff1d(c1,c2)

array([30, 50])

# Process Elements on Conditions¶


In [272]:
a = np.array([1,2,3,6,8])
b = np.array([10,2,30,60,8])

In [274]:
np.where(a==b) #returns the indices of elements in an input array where the given condition is satisfied.

(array([1, 4], dtype=int64),)

In [275]:
# Return an array where condition is satisfied
a[np.where(a==b)]

array([2, 8])

In [276]:
# Return all numbers betweeen 20 & 35
a1 = np.arange(0,60)
a1[np.where((a1>20)&(a1<35))]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [279]:
# Return all numbers betweeen 20 & 35 OR numbers divisible by 10
a1[np.where(((a1>20)&(a1<35)) | (a1%10==0))]

array([30])

In [280]:
# Return all numbers betweeen 20 & 35 and numbers divisible by 10
a1[np.where(((a1>20)&(a1<35)) & (a1%10==0))]

array([30])

In [281]:
# Return all numbers betweeen 20 & 35 using np.logical_and
a1[np.where(np.logical_and(a1>20,a1<35))]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [282]:
# Return all numbers betweeen 20 & 35 using np.logical_or
a1[np.where(np.logical_or(a1>20,a1<35))]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

# Check for elements in an Array using isin()¶


In [283]:
a = np.array([10,20,30,40,50,60,70])


In [285]:
# Check whether number 11 & 20 are present in an array
np.isin(a,[11,20])

array([False,  True, False, False, False, False, False])

In [288]:
#Display the matching numbers
a[np.isin(a,20)]

array([20])

In [289]:
# Check whether number 33 is present in an array
a[np.isin(a,33)]

array([], dtype=int32)

In [290]:
np.isin(a,33)

array([False, False, False, False, False, False, False])

In [291]:
b = np.array([10,20,30,40,10,10,70,80,70,90])
b

array([10, 20, 30, 40, 10, 10, 70, 80, 70, 90])

In [292]:
# Check whether number 10 & 70 are present in an array
np.isin(b,[10,70])

array([ True, False, False, False,  True,  True,  True, False,  True,
       False])

In [293]:
# Display the indices where match occurred
np.where(np.isin(b,[10,70]))

(array([0, 4, 5, 6, 8], dtype=int64),)

In [294]:
# Display the matching values
b[np.where(np.isin(b, [10,70]))]

array([10, 10, 10, 70, 70])

In [295]:
# Display the matching values
b[np.isin(b, [10,70])]

array([10, 10, 10, 70, 70])

# Reverse Array¶


In [296]:
a4 = np.arange(10,30)
a4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [297]:
a4[::-1] 

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [299]:
#
np.flip(a4)


array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [300]:
a3 = np.array([[3,2,8,1] , [70,50,10,67] , [45,25,75,15] , [12,9,77,4]])
a3

array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15],
       [12,  9, 77,  4]])

In [301]:
# Reverse both ROW & COLUMN positions

np.flip(a3)

array([[ 4, 77,  9, 12],
       [15, 75, 25, 45],
       [67, 10, 50, 70],
       [ 1,  8,  2,  3]])

In [305]:
# Reverse both ROW & COLUMN positions
a3[::-1,::-1]

array([[ 4, 77,  9, 12],
       [15, 75, 25, 45],
       [67, 10, 50, 70],
       [ 1,  8,  2,  3]])

In [302]:
# Reverse ROW positions
a3[::-1,]

array([[12,  9, 77,  4],
       [45, 25, 75, 15],
       [70, 50, 10, 67],
       [ 3,  2,  8,  1]])

In [303]:
# Reverse COLUMN positions
a3[:,::-1]

array([[ 1,  8,  2,  3],
       [67, 10, 50, 70],
       [15, 75, 25, 45],
       [ 4, 77,  9, 12]])


# Sorting Array¶


In [306]:
a = np.array([10,5,2,22,12,92,17,33])


In [307]:
# Sort array in ascending order
np.sort(a)


array([ 2,  5, 10, 12, 17, 22, 33, 92])

In [308]:
a3 = np.array([[3,2,8,1] , [70,50,10,67] , [45,25,75,15]])
a3 

array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15]])

In [310]:
# Sort along rows

np.sort(a3)

array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75]])

In [311]:
## Sort along rows
np.sort(a3,axis=0)

array([[ 3,  2,  8,  1],
       [45, 25, 10, 15],
       [70, 50, 75, 67]])

In [312]:
# Sort in descending order
b = np.sort(a)
b[::-1]

array([92, 33, 22, 17, 12, 10,  5,  2])

In [313]:
# Sort in descending order
np.flip(b)

array([92, 33, 22, 17, 12, 10,  5,  2])

In [314]:
# Sort in descending order
a[::-1].sort()  # first reverse and than sort
a

array([92, 33, 22, 17, 12, 10,  5,  2])

# "N" Largest & Smallest Numbers in an Array

In [315]:
p = np.arange(0,50)
p 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [329]:
np.random.shuffle(p)
p

array([29, 33, 40, 42, 15, 26, 35, 30, 47, 12, 31,  4, 19, 43,  7, 44,  5,
       20, 23,  6, 14, 13, 16, 17,  9, 49, 41,  0, 39, 27, 22, 37, 18,  8,
        3, 36, 11, 21,  1, 24, 32, 25, 28, 10,  2, 48, 46, 45, 34, 38])

In [332]:
# Return "n" largest numbers in an Array
n=5
p[np.argsort(p)[-5:]]

array([45, 46, 47, 48, 49])

In [333]:
# Return "n" smallest numbers in an Array
n=5
p[np.argsort(-p)[-5:]]


array([4, 3, 2, 1, 0])

# Repeating Sequences¶


In [334]:
a5 = [10,20,30] 
a5


[10, 20, 30]

In [338]:
# Repeat whole array twice
np.tile(a5,2)

array([10, 20, 30, 10, 20, 30])

In [340]:
# Repeat each element in an array thrice
np.repeat(a5,3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

# Compare Arrays¶


In [341]:
d1 = np.arange(0,10)
d2 = np.arange(0,10)
d3 = np.arange(10,20)
d4 = d1[::-1]

In [342]:
# Compare arrays using "allclose" function. If this function returns True then Arrays are equal
res1 = np.allclose(d1,d2)
res1 

True

In [345]:
# Compare arrays using "allclose" function. If this function returns True then Arrays are equal
res2 = np.allclose(d1,d3)
res2 

False

In [344]:
# Compare arrays using "allclose" function. If this function returns True then Arrays are equal
res3 = np.allclose(d1,d4)
res3 

False

# Frequent Values in an Array¶


In [347]:
# unique numbers in an array
b = np.array([10,10,10,20,30,20,30,30,20,10,10,30,10])
np.unique(b)

array([10, 20, 30])

In [349]:
# unique numbers in an array along with the count E.g value 10 occurred maximum times (5 times) in an array "b"
val,count = np.unique(b,return_counts=True)
val,count 

(array([10, 20, 30]), array([6, 3, 4], dtype=int64))

In [361]:
# 10 is the most frequent value 
np.bincount(b).argmax()

10

# Read-Only Array¶


In [373]:
d6 = np.arange(10,100,10)
d5 

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [377]:
# arrays mmutable  
d5=np.append(d5,[1,2])

In [379]:
# arrays arrays immutable
d5.flags.writeable = False


In [380]:
d5

array([10, 20, 30, 40, 50, 60, 70, 80, 90,  1,  2])

In [381]:
d5[0]=99

ValueError: assignment destination is read-only

# Vector

### Vector Addition¶


In [382]:
v1 = np.array([1,2])
v2 = np.array([3,4])
v1+v2 

array([4, 6])

In [384]:
v3 = np.add(v1,v2)

In [385]:
print("v3=",v3)

v3= [4 6]


### Multiplication of vectors¶


In [386]:
a1 = [1,2,3]
a2 = [4,5,6]
a3 = [4,5,4,5]

print(np.multiply(a1,a2))

[ 4 10 18]


### Dot Product¶


In [393]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

dotp = a1@a2
print("Dot product-",dotp)

dotp = np.dot(a1,a2)
print("Dot product using np.dot",dotp)

dotp = np.inner(a1,a2)
print(" Dot product usign np.inner", dotp)

dotp = sum(np.multiply(a1,a2))
print(" Dot product usign np.multiply & sum",dotp)

dotp = np.matmul(a1,a2)
print(" Dot product usign np.matmul",dotp)


dotp = 0
for i in range(len(a1)):
    dotp = dotp + a1[i]*a2[i]
print(" Dot product usign for loop" , dotp)


Dot product- 32
Dot product using np.dot 32
 Dot product usign np.inner 32
 Dot product usign np.multiply & sum 32
 Dot product usign np.matmul 32
 Dot product usign for loop 32


### Length of Vector¶


In [395]:
v3 = np.array([1,2,3,4,5,6])
length = np.sqrt(np.dot(v3,v3))
length

9.539392014169456

In [396]:
v3 = np.array([1,2,3,4,5,6])
length = np.sqrt(sum(np.multiply(v3,v3)))
length

9.539392014169456

In [397]:
v3 = np.array([1,2,3,4,5,6])
length = np.sqrt(np.matmul(v3,v3))
length

9.539392014169456

### Normalized Vector¶


In [401]:
v1 = [2,3]
length_v1 = np.sqrt(np.dot(v1,v1))
length_v1 
norm_v1 = v1/length_v1
norm_v1

array([0.5547002 , 0.83205029])

In [403]:
#Second Method
v1 = [2,3]
norm_v1 = v1/np.linalg.norm(v1)
norm_v1

array([0.5547002 , 0.83205029])

### Angle between vectors¶


In [410]:
#Second Method
v1 = np.array([4,3])
v2 = np.array([-3,4])
lengthV1 = np.sqrt(np.dot(v1,v1)) 
lengthV2  = np.sqrt(np.dot(v2,v2))
lengthV2 
np.rad2deg(np.arccos( np.dot(v1,v2) / (lengthV1 * lengthV2)))

90.0

### Inner & outer products¶


In [411]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.inner(v1,v2)

print("\n Inner Product ==>  \n", np.inner(v1,v2))
print("\n Outer Product ==>  \n", np.outer(v1,v2))


 Inner Product ==>  
 32

 Outer Product ==>  
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


### Vector Cross Product¶


In [413]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.cross(v1,v2)
print("\nVector Cross Product ==>  \n", np.cross(v1,v2))



Vector Cross Product ==>  
 [-3  6 -3]


# Matrix Creation¶


In [415]:
# Create a 4x4 matrix
A = np.array([[1,2,3,4],[5,6,7,8],[11,12,1,3],[140,130,11,22]])
A

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [ 11,  12,   1,   3],
       [140, 130,  11,  22]])

In [416]:
# Datatype of Matrix
A.dtype

dtype('int32')

In [417]:
# Shape of Matrix
A.shape

(4, 4)

In [424]:
B = np.array([[1.5,2.07,3,4] , [3,6,7,8] , [10 , 11 , 12 ,13] , [14,15,16,17]])
B

array([[ 1.5 ,  2.07,  3.  ,  4.  ],
       [ 3.  ,  6.  ,  7.  ,  8.  ],
       [10.  , 11.  , 12.  , 13.  ],
       [14.  , 15.  , 16.  , 17.  ]])

In [425]:
B.dtype

dtype('float64')

In [418]:
# Generate a 4x4 zero matrix
zero_mat = np.zeros(16).reshape(4,4)
zero_mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [427]:
# Generate a 5x5 matrix filled with ones
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [431]:
# Return 10x10 matrix of random integer numbers between 0 to 500
np.random.randint(0,500,(10,10))

array([[ 57, 203, 209,  44, 374,  14, 497,  44, 493, 151],
       [124, 236, 226, 126, 273, 425, 412, 462,  73,  87],
       [207, 490, 101,  19, 418,  59, 260,  54, 296, 232],
       [153,  32, 363, 209,  72, 424, 141, 458, 137, 459],
       [ 83, 478, 407, 480,  25, 468, 261, 174,   8, 100],
       [112, 352, 333, 225, 100, 426,   5, 145, 300, 490],
       [ 37, 186, 331, 468, 116, 204, 395, 338,  83, 297],
       [152, 424, 146, 189, 427, 385, 304,  16, 254,  15],
       [ 85,  74, 499, 487,  68,  37,  34, 497, 194, 373],
       [447, 113, 493,   0, 449, 100, 216, 320,  61, 244]])

In [432]:
arr2


array([16,  6,  1])

In [434]:
arr2.reshape(3,1)


array([[16],
       [ 6],
       [ 1]])

In [435]:
mat1 = np.random.randint(0,1000,100).reshape(10,10)
mat1

array([[482, 314, 315, 568, 367, 379,  14, 553, 289, 911],
       [208, 225, 539, 859, 457, 448, 401, 403, 711, 586],
       [ 94, 284, 294, 625, 767, 856, 415, 484, 493,   2],
       [599, 495, 827, 212, 191,  73, 704, 246, 891, 450],
       [659, 673, 426, 559, 406, 893, 173, 393,  72, 507],
       [716, 826, 120, 592, 451, 286, 909, 109, 567, 411],
       [475, 963, 791, 985, 184,  71, 685, 656, 507, 340],
       [344, 739, 683, 577, 280, 202, 178, 304, 920, 701],
       [ 28, 501, 514, 364, 355, 181, 138, 538, 177,  42],
       [578, 595,  62, 855, 778, 899, 507, 981, 457, 619]])

In [436]:
# accesing the element
mat1[0,0]

482

In [437]:
mat1[mat1 > 500]


array([568, 553, 911, 539, 859, 711, 586, 625, 767, 856, 599, 827, 704,
       891, 659, 673, 559, 893, 507, 716, 826, 592, 909, 567, 963, 791,
       985, 685, 656, 507, 739, 683, 577, 920, 701, 501, 514, 538, 578,
       595, 855, 778, 899, 507, 981, 619])

In [438]:
# Identity Matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [439]:
# Diagonal Matrix
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [444]:
# Traingular Matrices (lower & Upper triangular matrix)
M = np.random.randn(5,5)
U = np.triu(M)
L= np.tril(M)
M,U,L

(array([[-1.53202911,  0.08139478, -0.88963098,  0.2984396 ,  1.10497574],
        [-0.79062048, -0.05983992,  0.47617857,  0.29768454, -0.46671186],
        [ 0.35445818,  1.15783267,  1.64570109,  1.70186353, -0.5426648 ],
        [-0.16540875, -0.45667644,  0.50870018,  1.20038533, -1.56559407],
        [ 0.8091963 ,  0.01634763,  0.5234847 ,  0.78707916, -0.16521803]]),
 array([[-1.53202911,  0.08139478, -0.88963098,  0.2984396 ,  1.10497574],
        [ 0.        , -0.05983992,  0.47617857,  0.29768454, -0.46671186],
        [ 0.        ,  0.        ,  1.64570109,  1.70186353, -0.5426648 ],
        [ 0.        ,  0.        ,  0.        ,  1.20038533, -1.56559407],
        [ 0.        ,  0.        ,  0.        ,  0.        , -0.16521803]]),
 array([[-1.53202911,  0.        ,  0.        ,  0.        ,  0.        ],
        [-0.79062048, -0.05983992,  0.        ,  0.        ,  0.        ],
        [ 0.35445818,  1.15783267,  1.64570109,  0.        ,  0.        ],
        [-0.16540875,

In [448]:
# Generate a 5X5 matrix with a given fill value of 8
np.full((5,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [449]:
# Generate 5X5 matrix of Random float numbers between 10 to 20
np.random.uniform(10,20,size=(5,5))

array([[16.09502289, 12.06172523, 19.17342888, 14.92219351, 18.88851421],
       [19.49525442, 15.06221916, 13.75261205, 12.12651836, 12.1200072 ],
       [16.01172512, 12.91463287, 10.25590248, 19.99851933, 11.83168031],
       [18.35476533, 13.14119241, 14.59688826, 15.2207962 , 17.60468011],
       [10.88225591, 16.54403233, 17.15306923, 10.28797532, 19.37220067]])

In [450]:
A

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [ 11,  12,   1,   3],
       [140, 130,  11,  22]])

In [452]:
# Collapse Matrix into one dimension array
A.flatten()

array([  1,   2,   3,   4,   5,   6,   7,   8,  11,  12,   1,   3, 140,
       130,  11,  22])

In [453]:
# Collapse Matrix into one dimension array
A.ravel()

array([  1,   2,   3,   4,   5,   6,   7,   8,  11,  12,   1,   3, 140,
       130,  11,  22])

# Reading elements of a Matrix¶


In [454]:
A

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [ 11,  12,   1,   3],
       [140, 130,  11,  22]])

In [455]:
# Fetch first row of matrix
A[0]

array([1, 2, 3, 4])

In [456]:
A[0,]

array([1, 2, 3, 4])

In [457]:
# Fetch first column of matrix
A[:,0]

array([  1,   5,  11, 140])

In [458]:
# Fetch first element of the matrix
A[0,0]

1

In [459]:
A[1:3 , 1:3]

array([[ 6,  7],
       [12,  1]])

### Reverse Rows / Columns of a Matrix¶


In [460]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [462]:
# Reverse rows
arr[::-1]

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [463]:
#Reverse Columns
arr[:, ::-1]



array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])

### SWAP Rows & Columns¶


In [464]:
m1 = np.arange(0,16).reshape(4,4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [473]:
# SWAP rows 0 & 1
m1[[1,0]] = m1[[0,1]]
m1

array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [478]:
# SWAP rows 2 & 3
m1[[3,2]] = m1[[2,3]]
m1


array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11]])

In [479]:
m2 = np.arange(0,36).reshape(6,6)
m2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [480]:
# Swap columns 0 & 1
m2[:,[0,1]]=m2[:,[1,0]]
m2

array([[ 1,  0,  2,  3,  4,  5],
       [ 7,  6,  8,  9, 10, 11],
       [13, 12, 14, 15, 16, 17],
       [19, 18, 20, 21, 22, 23],
       [25, 24, 26, 27, 28, 29],
       [31, 30, 32, 33, 34, 35]])

### Concatenate Matrices¶


In [485]:
A = np.array([[1,2] , [3,4] ,[5,6]])
B = np.array([[1,1] , [1,1]])
c = np.concatenate((A,B))  
c


array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 1],
       [1, 1]])

### Matrix Addition¶


In [487]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])

print("\n First Matrix (M)  ==>  \n", M)
print("\n Second Matrix (N)  ==>  \n", N)

C = M+N
print("\n Matrix Addition (M+N)  ==>  \n", C)

# OR

C = np.add(M,N,dtype = np.float64)
print("\n Matrix Addition using np.add  ==>  \n", C)


 First Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

 Second Matrix (N)  ==>  
 [[1 1 1]
 [2 2 2]
 [3 3 3]]

 Matrix Addition (M+N)  ==>  
 [[ 2  3  4]
 [ 6 -1  8]
 [10 11  3]]

 Matrix Addition using np.add  ==>  
 [[ 2.  3.  4.]
 [ 6. -1.  8.]
 [10. 11.  3.]]


### Matrix subtraction

In [488]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])

print("\n First Matrix (M)  ==>  \n", M)
print("\n Second Matrix (N)  ==>  \n", N)

C = M-N
print("\n Matrix subtraction (M-N)  ==>  \n", C)

# OR

C = np.subtract(M,N,dtype = np.float64)
print("\n Matrix subtraction using np.subtract  ==>  \n", C)


 First Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

 Second Matrix (N)  ==>  
 [[1 1 1]
 [2 2 2]
 [3 3 3]]

 Matrix subtraction (M-N)  ==>  
 [[ 0  1  2]
 [ 2 -5  4]
 [ 4  5 -3]]

 Matrix subtraction using np.subtract  ==>  
 [[ 0.  1.  2.]
 [ 2. -5.  4.]
 [ 4.  5. -3.]]


### Matrices Scalar Multiplication¶


In [495]:
#Matrices Scalar Multiplication

M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
C = 10

print("\n Matrix (M)  ==>  \n", M)

print("\n Matrices Scalar Multiplication ==>\n", C*M)

#or

print("\nMatrices Scalar Multiplication ==>  \n", np.multiply(C,M))





 Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

 Matrices Scalar Multiplication ==>
 [[ 10  20  30]
 [ 40 -30  60]
 [ 70  80   0]]

Matrices Scalar Multiplication ==>  
 [[ 10  20  30]
 [ 40 -30  60]
 [ 70  80   0]]


### Transpose of a matrix


In [497]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
print("\n Matrix (M)  ==>  \n", M)

print("\nTranspose of M ==>  \n", np.transpose(M))

# OR

print("\nTranspose of M ==>  \n", M.T)


 Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Transpose of M ==>  
 [[ 1  4  7]
 [ 2 -3  8]
 [ 3  6  0]]

Transpose of M ==>  
 [[ 1  4  7]
 [ 2 -3  8]
 [ 3  6  0]]


### Determinant of a matrix¶


In [498]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])

print("\n Matrix (M)  ==>  \n", M)

print("\nDeterminant of M ==>  ", np.linalg.det(M))


 Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Determinant of M ==>   195.0


### Rank of a matrix¶


In [499]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
print("\n Matrix (M)  ==>  \n", M)
print("\nRank of M ==> ", np.linalg.matrix_rank(M))



 Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Rank of M ==>  3


### Trace of matrix


M = np.array([[1,2,3],[4,-3,6],[7,8,0]])

print("\n Matrix (M)  ==>  \n", M)

print("\nTrace of M ==> ", np.trace(M))

### Inverse of matrix A¶


In [501]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
print("\n Matrix (M)  ==>  \n", M)
print("\nInverse of M ==> \n", np.linalg.inv(M))



 Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Inverse of M ==> 
 [[-0.24615385  0.12307692  0.10769231]
 [ 0.21538462 -0.10769231  0.03076923]
 [ 0.27179487  0.03076923 -0.05641026]]


### Matrix Multiplication (pointwise multiplication)


In [503]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])

print("\n First Matrix (M)  ==>  \n", M)
print("\n Second Matrix (N)  ==>  \n", N)

print("\n Point-Wise Multiplication of M & N  ==> \n", M*N)

# OR

print("\n Point-Wise Multiplication of M & N  ==> \n", np.multiply(M,N))


 First Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

 Second Matrix (N)  ==>  
 [[1 1 1]
 [2 2 2]
 [3 3 3]]

 Point-Wise Multiplication of M & N  ==> 
 [[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]

 Point-Wise Multiplication of M & N  ==> 
 [[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]


### Matrix dot product¶


In [504]:

M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])

print("\n First Matrix (M)  ==>  \n", M)
print("\n Second Matrix (N)  ==>  \n", N)

print("\n Matrix Dot Product ==> \n", M@N)

# OR

print("\n Matrix Dot Product using np.matmul ==> \n", np.matmul(M,N))

# OR

print("\n Matrix Dot Product using np.dot ==> \n", np.dot(M,N))


 First Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

 Second Matrix (N)  ==>  
 [[1 1 1]
 [2 2 2]
 [3 3 3]]

 Matrix Dot Product ==> 
 [[14 14 14]
 [16 16 16]
 [23 23 23]]

 Matrix Dot Product using np.matmul ==> 
 [[14 14 14]
 [16 16 16]
 [23 23 23]]

 Matrix Dot Product using np.dot ==> 
 [[14 14 14]
 [16 16 16]
 [23 23 23]]


### Matrix Division¶
 

In [505]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])

print("\n First Matrix (M)  ==>  \n", M)
print("\n Second Matrix (N)  ==>  \n", N)


print("\n Matrix Division (M/N)   ==> \n", M/N)

# OR

print("\n Matrix Division (M/N)   ==> \n", np.divide(M,N))


 First Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

 Second Matrix (N)  ==>  
 [[1 1 1]
 [2 2 2]
 [3 3 3]]

 Matrix Division (M/N)   ==> 
 [[ 1.          2.          3.        ]
 [ 2.         -1.5         3.        ]
 [ 2.33333333  2.66666667  0.        ]]

 Matrix Division (M/N)   ==> 
 [[ 1.          2.          3.        ]
 [ 2.         -1.5         3.        ]
 [ 2.33333333  2.66666667  0.        ]]


### Sum of all elements in a matrix¶


In [506]:
N = np.array([[1,1,1],[2,2,2],[3,3,3]])

print("\n Matrix (N)  ==>  \n", N)


print ("Sum of all elements in a Matrix  ==>")
print (np.sum(N))


 Matrix (N)  ==>  
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
Sum of all elements in a Matrix  ==>
18


### Column wise Sum

In [509]:
N= np.array([[1,1,1],[2,2,2],[3,3,3]])

print("\n Matrix (N)  ==>  \n", N)

print ("Column-Wise summation ==> ")
print (np.sum(N,axis=0))


 Matrix (N)  ==>  
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
Column-Wise summation ==> 
[6 6 6]


### Row wise Sum

In [508]:
N = np.array([[1,1,1],[2,2,2],[3,3,3]])

print("\n Matrix (N)  ==>  \n", N)

print ("Row-Wise summation  ==>")
print (np.sum(N,axis=1))


 Matrix (N)  ==>  
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
Row-Wise summation  ==>
[3 6 9]


### Matrix Powers¶


In [510]:
M1 = np.array([[1,2],[4,5]])
M1

array([[1, 2],
       [4, 5]])

In [511]:
#Matrix to the power 2

M1@M1


array([[ 9, 12],
       [24, 33]])

In [512]:
#Matrix to the power 

M1@M1@M1


array([[ 57,  78],
       [156, 213]])

In [513]:
#Matrix to the power 3

np.linalg.matrix_power(M1,3)

array([[ 57,  78],
       [156, 213]])

# Tensor

In [514]:
# Create Tensor

T1 = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[10,20,30], [40,50,60], [70,80,90]],
  [[100,200,300], [400,500,600], [700,800,900]],
  ])

T1

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]],

       [[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [516]:
T2 = np.array([
    [[0,0,0],[0,0,0],[0,0,0]],
    [[1,1,1],[1,1,1],[1,1,1]],
    [[2,2,2],[2,2,2],[2,2,2]]
        
])

T2

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

### Tensor Addition¶


In [517]:
A = T1+T2
A

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

In [518]:
np.add(T1,T2)


array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

### Tensor Subtraction

In [520]:
B= T1-T2
B

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[  9,  19,  29],
        [ 39,  49,  59],
        [ 69,  79,  89]],

       [[ 98, 198, 298],
        [398, 498, 598],
        [698, 798, 898]]])

In [521]:
np.subtract(T1,T2)

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[  9,  19,  29],
        [ 39,  49,  59],
        [ 69,  79,  89]],

       [[ 98, 198, 298],
        [398, 498, 598],
        [698, 798, 898]]])

### Tensor Dot Product¶


In [522]:
np.tensordot(T1,T2)

array([[  63,   63,   63],
       [ 630,  630,  630],
       [6300, 6300, 6300]])

### Solving Equations              ************************                   AX=B

In [540]:
A = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [541]:
B = np.random.random((3,1))
B

array([[0.05480935],
       [0.8055286 ],
       [0.7895299 ]])

In [542]:
# 1st method to find x

X = np.dot(np.linalg.inv(A) , B)
X

LinAlgError: Singular matrix

A singular matrix is a matrix that cannot be inverted, or, equivalently, that has determinant zero. For this reason, you cannot solve a system of equations using a singular matrix (it may have no solution or multiple solutions, but in any case no unique solution)

In [545]:
# 2nd method 
A = np.array([[1,2,3] , [43,5,6] , [7,8,9]])
A
B = np.random.random((3,1))
B
X = np.linalg.inv(A)@B
X

# 3rd method
X = np.matmul(np.linalg.inv(A) , B)
X

array([[ 0.00795263],
       [-0.04664358],
       [ 0.05937991]])

# END