
#                                            Numpy Tutorial 

# Why use NumPy?

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

In [37]:
import numpy as np 
import math 
import warnings
warnings.filterwarnings("ignore")
from IPython.display import Image

## 1D array, 2D array, ndarray, vector, matrix,Tensors

A vector is an array with a single dimension (there’s no difference between row and column vectors), while a matrix refers to an array with two dimensions. For 3-D or higher dimensional arrays, the term tensor is also commonly used.

## Create a basic array
This section covers np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype



In [45]:
list1 = [10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [46]:
# Display the type of an object
type(list1)

list

In [47]:
#Convert list to Numpy Array
arr1 = np.array(list1)

In [48]:
#Memory address of an array object
arr1.data

In [49]:
# Display type of an object
type(arr1)

numpy.ndarray

In [51]:
#Datatype of array
arr1.dtype

dtype('int32')

In [52]:
# Convert Integer Array to FLOAT
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [53]:
# Generate evenly spaced numbers (space =1) between 0 to 10
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
# Generate numbers between 0 to 100 with a space of 10
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [55]:
# Generate numbers between 10 to 100 with a space of 10 in descending order
np.arange(100,10,-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [59]:
arr2 = np.array([[1,2,3],[1,1,1]])
arr2 

array([[1, 2, 3],
       [1, 1, 1]])

In [60]:
#Shape of Array
arr1.shape , arr2.shape

((6,), (2, 3))

In [61]:
# Size of array
arr1.size , arr2.size

(6, 6)

In [62]:
# Dimension 
arr1.ndim , arr2.ndim 

(1, 2)

In [65]:
# Datatype of object
arr2.dtype

dtype('int32')

In [66]:
# Bytes consumed by one element of an array object
arr2.itemsize

4

In [69]:
# Bytes consumed by an array object
arr2.nbytes

24

In [73]:
# length of array
len(arr2)


2

In [76]:
# Generate an array of zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [82]:
# Generate an array of ones with given shape
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [85]:
# Repeat 10 five times in an array
np.repeat(10,3)

array([10, 10, 10])

In [86]:
# Repeat each element in array/list 'b' thrice
b = [1,2,3,4]
np.repeat(b,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [87]:
# Array of 10's
np.full(3,10)


array([10, 10, 10])

In [90]:
np.ones_like(10)

array(1)

In [92]:
# Generate array of Odd numbers
ar1 = np.arange(1,20)
ans = ar1[ar1%2==1]
ans

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [93]:
# Generate array of even numbers
ar1 = np.arange(1,20)
ar1[ar1%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [94]:
# Generate evenly spaced 4 numbers between 10 to 20.
np.linspace(10,20,4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [95]:
# Generate evenly spaced 11 numbers between 10 to 20.
np.linspace(10,20,15)


array([10.        , 10.71428571, 11.42857143, 12.14285714, 12.85714286,
       13.57142857, 14.28571429, 15.        , 15.71428571, 16.42857143,
       17.14285714, 17.85714286, 18.57142857, 19.28571429, 20.        ])

In [96]:
# Create an array of random values
np.random.random(4)


array([0.70130884, 0.44175175, 0.22345572, 0.16067744])

In [98]:
# Generate an array of Random Integer numbers
np.random.randint(0,100,6)

array([ 3, 86,  8, 38, 80, 27])

In [112]:
# Using random.seed we can generate same number of Random numbers
np.random.seed(123)
np.random.randint(0,100,10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [110]:
np.random.randn(10)

array([-0.2299375 , -1.28359884, -2.71119174, -1.52241044, -1.41620705,
        1.10854366,  1.13102858,  0.49860031,  1.17902193,  1.32268437])

In [129]:
# Generate array of Random float numbers
f1 = np.random.uniform(5,10,10)
f1

array([9.34521773, 5.67478125, 7.91051226, 7.81108133, 5.4518006 ,
       8.82082369, 7.36455072, 8.07414876, 8.63097521, 6.60744156])

In [130]:
# Extract Integer part
np.floor(f1)

array([9., 5., 7., 7., 5., 8., 7., 8., 8., 6.])

In [131]:
# Truncate decimal part
np.trunc(f1)

array([9., 5., 7., 7., 5., 8., 7., 8., 8., 6.])

In [132]:
# Convert Float Array to Integer array
f1.astype(int)

array([9, 5, 7, 7, 5, 8, 7, 8, 8, 6])

In [141]:
# Normal distribution (mean=0 and variance=1)
b2 = np.random.randn(10)
b2

array([ 0.34020214, -1.13320326, -0.44388393,  2.28008424, -0.76230112,
        0.117435  , -0.65094869,  0.45886268, -0.61012018, -0.2339279 ])

In [144]:
# Enumerate for Numpy Arrays
for index,value in np.ndenumerate(b2):
    print(index,value)

(0,) 0.3402021440266375
(1,) -1.1332032553014906
(2,) -0.4438839252596832
(3,) 2.280084244216001
(4,) -0.7623011246188897
(5,) 0.11743499605854721
(6,) -0.6509486881811433
(7,) 0.45886267620982396
(8,) -0.6101201827305474
(9,) -0.23392790107076064
