
#                                            Numpy Tutorial 

# Why use NumPy?

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

In [37]:
import numpy as np 
import math 
import warnings
warnings.filterwarnings("ignore")
from IPython.display import Image

## 1D array, 2D array, ndarray, vector, matrix,Tensors

A vector is an array with a single dimension (there’s no difference between row and column vectors), while a matrix refers to an array with two dimensions. For 3-D or higher dimensional arrays, the term tensor is also commonly used.

## Create a basic array
This section covers np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype



In [45]:
list1 = [10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [46]:
# Display the type of an object
type(list1)

list

In [47]:
#Convert list to Numpy Array
arr1 = np.array(list1)

In [48]:
#Memory address of an array object
arr1.data

In [49]:
# Display type of an object
type(arr1)

numpy.ndarray

In [51]:
#Datatype of array
arr1.dtype

dtype('int32')

In [52]:
# Convert Integer Array to FLOAT
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [53]:
# Generate evenly spaced numbers (space =1) between 0 to 10
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
# Generate numbers between 0 to 100 with a space of 10
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [55]:
# Generate numbers between 10 to 100 with a space of 10 in descending order
np.arange(100,10,-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [59]:
arr2 = np.array([[1,2,3],[1,1,1]])
arr2 

array([[1, 2, 3],
       [1, 1, 1]])

In [60]:
#Shape of Array
arr1.shape , arr2.shape

((6,), (2, 3))

In [61]:
# Size of array
arr1.size , arr2.size

(6, 6)

In [62]:
# Dimension 
arr1.ndim , arr2.ndim 

(1, 2)

In [65]:
# Datatype of object
arr2.dtype

dtype('int32')

In [66]:
# Bytes consumed by one element of an array object
arr2.itemsize

4

In [69]:
# Bytes consumed by an array object
arr2.nbytes

24

In [73]:
# length of array
len(arr2)


2

In [76]:
# Generate an array of zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [82]:
# Generate an array of ones with given shape
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [85]:
# Repeat 10 five times in an array
np.repeat(10,3)

array([10, 10, 10])

In [86]:
# Repeat each element in array/list 'b' thrice
b = [1,2,3,4]
np.repeat(b,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [87]:
# Array of 10's
np.full(3,10)


array([10, 10, 10])

In [90]:
np.ones_like(10)

array(1)

In [92]:
# Generate array of Odd numbers
ar1 = np.arange(1,20)
ans = ar1[ar1%2==1]
ans

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [93]:
# Generate array of even numbers
ar1 = np.arange(1,20)
ar1[ar1%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])