# Why use NumPy?

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

In [1]:
%pwd 


'D:\\ALcala_AI_DL\\Github_portfolio\\MachineLearning'

In [2]:
import numpy as np 
import math 

## 1D array, 2D array, ndarray, vector, matrix,Tensors

A vector is an array with a single dimension (there’s no difference between row and column vectors), while a matrix refers to an array with two dimensions. For 3-D or higher dimensional arrays, the term tensor is also commonly used.

## Create a basic array
This section covers np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype



In [19]:
a = np.array([1,2,3,4])
a.shape

(4,)

In [18]:
np.zeros(2)

array([0., 0.])

In [20]:
np.ones(2)

array([1., 1.])

In [21]:
np.arange(4)

array([0, 1, 2, 3])

In [24]:
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [29]:
np.linspace(0,10,12)

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ])

In [34]:
x = np.ones(3,dtype = np.double)

In [35]:
x

array([1., 1., 1.])